apiVersion: batch/v1
kind: Job
metadata:
  name: beam
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: tokenizer
          image: tokenizer
          command:
            - ./tokenizer
          env:
            - name: SOURCE
              value: "redmed_lexicon.tsv"
            - name: TARGET
              value: "drugs.csv"
            - name: COLUMNS
              value: "1,3,4,5"
          envFrom:
            - configMapRef:
                name: job-config
