apiVersion: batch/v1
kind: Job
metadata:
  name: pipeline
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: pipeline
          image: pipeline
          command:
            - ./pipeline
          envFrom:
            - configMapRef:
                name: pipeline-config
