apiVersion: batch/v1
kind: Job
metadata:
  name: tokenizer
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: tokenizer
          image: tokenizer
          command:
            - ./tokenizer
          envFrom:
            - configMapRef:
                name: tokenizer-config
